// src/data/hospitalData.js
import Maximg from "../../../assets/Max.jpg"

const hospitalData = [
    {
      _id: 1,
      name: 'AIIMs Delhi',
      bed: 100,
      totalbed: 120,
      embed: 10,
      emtotalbed: 12,
      discription: 'Description A',
      Special: 'Heart special/ General / Emergency',
      location:'Delhi',
      image: Maximg,
      contact: '+91-47382937483',
    },
    {
      _id: 2,
      name: 'Hings Hospital',
      bed: 200,
      totalbed: 400,
      embed: 10,
      emtotalbed: 12,
      discription: 'Description B',
      Special: 'Heart special/ General / Emergency',
      location:'Varanasi, UP',
      image: Maximg,
      contact: '+91-47382937483',
    },
    {
      _id: 3,
      name: 'Urgency-aid Hospital',
      bed: 300,
      totalbed: 400,
      embed: 10,
      emtotalbed: 12,
      discription: 'Description C',
      Special: 'Heart special/ General / Emergency',
      location:'Delhi',
      image: Maximg,
      contact: '+91-47382937483',
    },
    {
        _id: 4,
        name: 'Fellis Healthcare',
        bed: 100,
        totalbed: 120,
        embed: 10,
        emtotalbed: 12,
        discription: 'Description A',
        Special: 'Heart special/ General / Emergency',
        location:'Greater Noida, Up',
        image: Maximg,
        contact: '+91-47382937483',
      },
      {
        _id: 5,
        name: "Grit-India Hospitals",
        bed: 200,
        totalbed: 400,
        embed: 10,
        emtotalbed: 12,
        discription: 'Description B',
        Special: 'Heart special/ General / Emergency',
        location:'Surat, Gujarat',
        image: Maximg,
        contact: '+91-47382937483',
      },
      {
        _id: 6,
        name: "GEU Hospitals",
        bed: 150,
        totalbed: 300,
        embed: 10,
        emtotalbed: 12,
        discription: 'Description C',
        Special: 'Heart special/ General / Emergency',
        location:'Dehradun, Uttarakhand',
        image: Maximg,
        contact: '+91-47382937483',
      },
      {
        _id: 7,
          name: "Ramvati Hospital",
        bed: 7,
        totalbed: 100,
        embed: 7,
        emtotalbed: 15,
        discription: 'Description C',
        Special: 'Heart special/ General / Emergency',
        location:'Mumbai, Maharashtra',
        image: Maximg,
        contact: '+91-47382937483',
      },
      {
        _id: 8,
          name: "North East Hospital",
        bed: 10,
        totalbed: 120,
        embed: 20,
        emtotalbed: 50,
        discription: 'Description C',
        Special: 'Nurolofy/ General / Emergency',
        location:'Gangtok, Sikkim',
        image: Maximg,
        contact: '+91-47382937483',
      },
      {
        _id: 9,
          name: "Ahem Modi Hospital",
        bed: 50,
        totalbed: 140,
        embed: 0,
        emtotalbed: 0,
        discription: 'Description C',
        Special: 'Orthopedic/ General',
        location:'Gandhinagar, Gujarat',
        image: Maximg,
        contact: '+91-47382937483',
      },
      {
        _id: 10,
          name: "Apollo Hospital",
        bed: 13,
        totalbed: 60,
        embed: 0,
        emtotalbed: 0,
        discription: 'Description C',
        Special: 'Heart special/ General',
        location:'Varanasi, UP',
        image: Maximg,
        contact: '+91-47382937483',
      },
    // Add more items as needed
  ];
  
  export default hospitalData;
  